_target_: torch_mist.estimators.doe
hidden_dims: ${params.hidden_dims}
x_dim: ${metadata.x_dim}
y_dim: ${metadata.y_dim}
marginal_transform_name: ${params.marginal_transform_name}
conditional_transform_name: ${params.conditional_transform_name}