# @package _global_
defaults:
  - /quantization@mi_estimator.quantize_y: kmeans

mi_estimator:
  _target_: torch_mist.estimators.pq
  x_dim: ${metadata.x_dim}
  hidden_dims: ${params.hidden_dims}
  temperature: ${params.temperature}
