name: dl-kit
channels:
  - pytorch
  - defaults
dependencies:
  - pip=20.0.2
  - pytorch-cuda=11.4
  - python=3.8.1
  - pip:
    - jsonargparse[signatures]
    - matplotlib==3.1.3
    - numpy==1.24.0
    - omegaconf==2.1.1
    - pandas==1.5.2
    - plotly==4.8.1
    - pyro-ppl==1.8.3
    - pytorch-lightning==1.8.5.post0
    - scikit-learn==0.22.1
    - scipy==1.8.0
    - seaborn==0.12.1
    - sklearn==0.0
    - tqdm==4.64.1
    - wandb==0.12.11 # Optional
