[tool.poetry]
name = "torch_mist"
version = "0.1.0"
description = "Mutual Information Estimation toolkit based on pytorch"
authors = ["Marco Federici"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
