class_path: core.models.mi_estimator.FLO
init_args:
  ratio_estimator:
    class_path: core.models.ratio.JointRatioEstimatorMLP
    init_args:
      x_dim: 30
      y_dim: 30
      hidden_dims: [256, 128]
  baseline:
    class_path: core.models.baseline.LearnableJointMLPBaseline
    init_args:
      x_dim: 30
      y_dim: 30
      hidden_dims: [256, 128]
