class_path: core.models.MutualInformationEstimator
init_args:
  ratio_estimator: ../ratio_estimators/joint.yaml
  baseline: ../baselines/batch_logmeanexp_2D.yaml
  js_grad: true
  tau: 5.0 # clipping the ratio between -tau and tau