class_path: core.models.mi_estimator.InfoNCE
init_args:
  ratio_estimator:
    class_path: core.models.ratio.SeparableRatioEstimatorMLP
    init_args:
      x_dim: 5
      y_dim: 5
      hidden_dims: [256, 128]
