class_path: core.models.mi_estimator.AlphaTUBA
init_args:
  ratio_estimator:
    class_path: core.models.ratio_estimator.SeparableRatioEstimatorMLP
    init_args:
      x_dim: 5
      y_dim: 5
      hidden_dims: [256, 128]
      out_dim: 64
      transform_y: True
  alpha: 0.5
  neg_samples: 0
