class_path: core.models.mi_estimator.SMILE
init_args:
  ratio_estimator:
    class_path: core.models.ratio_estimator.JointRatioEstimatorMLP
    init_args:
      x_dim: 5
      y_dim: 5
      hidden_dims: [256, 128]
  tau: 5
