class_path: core.models.mi_estimator.DoE
init_args:
  # Using a Normal distribution with learnable (conditional) mean and variance
  conditional_y_x:
    class_path: core.models.learnable_distributions.ConditionalFlowTransformedNormal
    init_args:
      y_dim: 64
      x_dim: 64
      hidden_dims: [512, 256]
      transform_name: conditional_linear
  marginal_y:
    class_path: core.models.learnable_distributions.FlowTransformedNormal
    init_args:
      input_dim: 64
      hidden_dims: [256, 128]
      transform_name: affine_autoregressive
      n_transforms: 3
