class_path: core.task.MutualInformationEstimator
init_args:
  ratio_estimator: ../models/ratio_estimators/joint.yaml
  baseline: ../models/baselines/batch_logmeanexp_2D.yaml
  grad_baseline: ../models/baselines/exp_average.yaml
