class_path: core.task.MutualInformationEstimator
init_args:
  ratio_estimator: ../models/ratio_estimators/joint.yaml
  baseline: ../models/baselines/one.yaml
  proposal: ../models/proposals/transformed_normal.yaml
  h_y: 5.311