class_path: core.models.mi_estimator.ABC
init_args:
  # Using a Normal distribution with learnable (conditional) mean and variance
  conditional_a_y:
    class_path: core.models.learnable_distributions.ConditionalCategoricalMLP
    init_args:
      y_dim: 5
      n_classes: 32
      hidden_dims: [256, 128]

