class_path: core.models.mi_estimator.GM
init_args:
  # Using a Normal distribution with learnable (conditional) mean and variance
  joint_xy:
    class_path: core.models.learnable_distributions.FlowTransformedJointNormal
    init_args:
      y_dim: 5
      x_dim: 5
      hidden_dims: [256, 128]
      transform_name: affine_autoregressive
      n_transforms: 3
  marginal_y:
    class_path: core.models.learnable_distributions.FlowTransformedNormal
    init_args:
      input_dim: 5
      hidden_dims: [128, 64]
      transform_name: affine_autoregressive
      n_transforms: 2
  marginal_x:
    class_path: core.models.learnable_distributions.FlowTransformedNormal
    init_args:
      input_dim: 5
      hidden_dims: [ 128, 64 ]
      transform_name: affine_autoregressive
      n_transforms: 2
